In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Sum of arrays:", arr1 + arr2)
print("Product of arrays:", arr1 * arr2)
print("Dot product of arrays:", np.dot(arr1, arr2))
print(type(arr1))
print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)
print("Are arr1 and arr2 equal?", np.array_equal(arr1, arr2))
print("Concatenated arrays:", np.concatenate((arr1, arr2)))
print("Mean of arr1:", np.mean(arr1))
print("Standard deviation of arr2:", np.std(arr2))

Sum of arrays: [5 7 9]
Product of arrays: [ 4 10 18]
Dot product of arrays: 32
<class 'numpy.ndarray'>
Shape of arr1: (3,)
Shape of arr2: (3,)
Are arr1 and arr2 equal? False
Concatenated arrays: [1 2 3 4 5 6]
Mean of arr1: 2.0
Standard deviation of arr2: 0.816496580927726


In [6]:
arr3 = np.array([[1,2,3], [4,5,6]])
print("shape of arr3: ", arr3.shape)
print("Transpose of arr3:\n", arr3.T)
print("Sum of arr3 along axis 0:", np.sum(arr3, axis=0))
print("Sum of arr3 along axis 1:", np.sum(arr3, axis=1))
print("Maximum value in arr1:", np.max(arr1))
print("Minimum value in arr2:", np.min(arr2))
print("Unique elements in arr1:", np.unique(arr1))
print("Index of maximum value in arr1:", np.argmax(arr1))
print("Index of minimum value in arr2:", np.argmin(arr2))
print("Flattened arr3:", arr3.flatten())
print("Reshaped arr1 to (3, 1):\n", arr1.reshape((3, 1)))
print("Element-wise square of arr1:", np.square(arr1))
print("Element-wise square root of arr2:", np.sqrt(arr2))
print("Logical AND of arr1 and arr2:", np.logical_and(arr1 > 1, arr2 < 6))
print("Logical OR of arr1 and arr2:", np.logical_or(arr1 < 2, arr2 > 5))
print("Logical NOT of arr1:", np.logical_not(arr1 > 2))


shape of arr3:  (2, 3)
Transpose of arr3:
 [[1 4]
 [2 5]
 [3 6]]
Sum of arr3 along axis 0: [5 7 9]
Sum of arr3 along axis 1: [ 6 15]
Maximum value in arr1: 3
Minimum value in arr2: 4
Unique elements in arr1: [1 2 3]
Index of maximum value in arr1: 2
Index of minimum value in arr2: 0
Flattened arr3: [1 2 3 4 5 6]
Reshaped arr1 to (3, 1):
 [[1]
 [2]
 [3]]
Element-wise square of arr1: [1 4 9]
Element-wise square root of arr2: [2.         2.23606798 2.44948974]
Logical AND of arr1 and arr2: [False  True False]
Logical OR of arr1 and arr2: [ True False  True]
Logical NOT of arr1: [ True  True False]


In [8]:
# random number generation
random_arr = np.random.rand(3, 3)
print("Random array:\n", random_arr)
print("Random number between 0 and 1:", np.random.rand())
print("Random integer between 0 and 10:", np.random.randint(0, 10))
print("Random sample from arr1:", np.random.choice(arr1))
print("Random sample from arr2 with replacement:", np.random.choice(arr2, size=5, replace=True))
print("Random sample from arr2 without replacement:", np.random.choice(arr2, size=3, replace=False))
print("Random permutation of arr1:", np.random.permutation(arr1))
print("Random seed set to 42")
np.random.seed(42)
print("Random number with seed 42:", np.random.rand())
print("Random integer with seed 42:", np.random.randint(0, 10))
print("Random sample from arr1 with seed 42:", np.random.choice(arr1))
print("Random sample from arr2 with replacement and seed 42:", np.random.choice(arr2, size=5, replace=True))
print("Random sample from arr2 without replacement and seed 42:", np.random.choice(arr2, size=3, replace=False))
print("Random permutation of arr1 with seed 42:", np.random.permutation(arr1))
print("Random array with normal distribution:\n", np.random.randn(3, 3))
print("Random array with uniform distribution:\n", np.random.uniform(0, 1, (3, 3)))
print("Random array with integers between 1 and 10:\n", np.random.randint(1, 10, (3, 3)))
print("Random choice from arr1 with probabilities [0.1, 0.2, 0.7]:", np.random.choice(arr1, p=[0.1, 0.2, 0.7]))
print("Random choice from arr2 with probabilities [0.5, 0.3, 0.2]:", np.random.choice(arr2, p=[0.5, 0.3, 0.2]))
print("Random sample from arr1 with size 2:", np.random.choice(arr1, size=2))
print("Random sample from arr2 with size 3:", np.random.choice(arr2, size=3))
print("Random sample from arr1 with replacement and size 4:", np.random.choice(arr1, size=4, replace=True))
print("Random sample from arr2 without replacement and size 2:", np.random.choice(arr2, size=2, replace=False))
print("Random permutation of arr1 with seed 42:\n", np.random.permutation(arr1))
print("Random permutation of arr2 with seed 42:\n", np.random.permutation(arr2))
print("Random array with integers between 1 and 100:\n", np.random.randint(1, 100, (3, 3)))
print("Random array with normal distribution (mean=0, std=1):\n", np.random.normal(0, 1, (3, 3)))
print("Random array with uniform distribution (low=0, high=10):\n", np.random.uniform(0, 10, (3, 3)))
# print("Random choice from arr1 with size 2 and probabilities [0.5, 0.5]:", np.random.choice(arr1, size=2, p=[0.5, 0.5]))
print("Random choice from arr2 with size 3 and probabilities [0.2, 0.3, 0.5]:", np.random.choice(arr2, size=3, p=[0.2, 0.3, 0.5]))
print("Random sample from arr1 with size 3 and replacement:", np.random.choice(arr1, size=3, replace=True))
print("Random sample from arr2 with size 2 and without replacement:", np.random.choice(arr2, size=2, replace=False))
print("Random permutation of arr1 with seed 42:\n", np.random.permutation(arr1))
print("Random permutation of arr2 with seed 42:\n", np.random.permutation(arr2))
print("Random array with integers between 10 and 50:\n", np.random.randint(10, 50, (3, 3)))
print("Random array with normal distribution (mean=5, std=2):\n", np.random.normal(5, 2, (3, 3)))
print("Random array with uniform distribution (low=1, high=100):\n", np.random.uniform(1, 100, (3, 3)))
print("Random choice from arr1 with size 3 and probabilities [0.2, 0.3, 0.5]:", np.random.choice(arr1, size=3, p=[0.2, 0.3, 0.5]))
print("Random choice from arr2 with size 2 and probabilities [0.1, 0.4, 0.5]:", np.random.choice(arr2, size=2, p=[0.1, 0.4, 0.5]))
print("Random sample from arr1 with size 4 and replacement:", np.random.choice(arr1, size=4, replace=True))

Random array:
 [[0.92630088 0.65107703 0.91495968]
 [0.85003858 0.44945067 0.09541012]
 [0.37081825 0.66884125 0.66592236]]
Random number between 0 and 1: 0.5912977877077271
Random integer between 0 and 10: 5
Random sample from arr1: 3
Random sample from arr2 with replacement: [6 4 6 4 6]
Random sample from arr2 without replacement: [6 4 5]
Random permutation of arr1: [2 3 1]
Random seed set to 42
Random number with seed 42: 0.3745401188473625
Random integer with seed 42: 7
Random sample from arr1 with seed 42: 1
Random sample from arr2 with replacement and seed 42: [4 6 5 6 6]
Random sample from arr2 without replacement and seed 42: [5 4 6]
Random permutation of arr1 with seed 42: [3 2 1]
Random array with normal distribution:
 [[ 0.39257975 -0.92918467  0.07983181]
 [-0.1595165   0.02222183 -0.42779291]
 [-0.53181741 -0.1174755   0.2220789 ]]
Random array with uniform distribution:
 [[0.38246199 0.98323089 0.46676289]
 [0.85994041 0.68030754 0.45049925]
 [0.01326496 0.94220176 0.5632

In [44]:
np.arange(10)  # Example of using np.arange
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [37]:
np.arange(24).reshape(4, 6) # Example of using np.arange with reshape

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [46]:
### Numpy Vectorized Operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Sum of arrays:", arr1 + arr2)
print("Difference of arrays:", arr1 - arr2)
print("Product of arrays:", arr1 * arr2)
print("Dot product of arrays:", np.dot(arr1, arr2))


Sum of arrays: [5 7 9]
Difference of arrays: [-3 -3 -3]
Product of arrays: [ 4 10 18]
Dot product of arrays: 32


In [47]:
# Attributes of numpy arrays
print("Type of arr1:", type(arr1))
print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)
print("Are arr1 and arr2 equal?", np.array_equal(arr1, arr2))
print("Concatenated arrays:", np.concatenate((arr1, arr2)))
print("Mean of arr1:", np.mean(arr1))
print("Standard deviation of arr2:", np.std(arr2))
# Example of using np.arange with reshape
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of arr3:", arr3.shape)
arr3_transpose = arr3.T
print("Transpose of arr3:\n", arr3_transpose)
dimen = arr3.ndim
print("Number of dimensions of arr3:", dimen)

item_size = arr3.itemsize
print("Item size of arr3:", item_size)
size = arr3.size
print("Total number of elements in arr3:", size)


Type of arr1: <class 'numpy.ndarray'>
Shape of arr1: (3,)
Shape of arr2: (3,)
Are arr1 and arr2 equal? False
Concatenated arrays: [1 2 3 4 5 6]
Mean of arr1: 2.0
Standard deviation of arr2: 0.816496580927726
Shape of arr3: (2, 3)
Transpose of arr3:
 [[1 4]
 [2 5]
 [3 6]]
Number of dimensions of arr3: 2
Item size of arr3: 8
Total number of elements in arr3: 6


In [48]:
# Numpy Vectorized Operations
arr4 = np.array([1, 2, 3])
arr5 = np.array([4, 5, 6])
print("Sum of arrays:", arr4 + arr5)
print("Difference of arrays:", arr4 - arr5)
print("Product of arrays:", arr4 * arr5)
print("Dot product of arrays:", np.dot(arr4, arr5))
print("Element-wise square of arr4:", np.square(arr4))
print("Division of arr5 by arr4:", arr5 / arr4)
print("Element-wise square root of arr5:", np.sqrt(arr5))

# Numpy Array Operations
# print("Logical AND of arr4 and arr5:", np.logical_and(arr4 > 1, arr5 < 6))
# print("Logical OR of arr4 and arr5:", np.logical_or(arr4 < 2, arr5 > 5))
# print("Logical NOT of arr4:", np.logical_not(arr4 > 2))

Sum of arrays: [5 7 9]
Difference of arrays: [-3 -3 -3]
Product of arrays: [ 4 10 18]
Dot product of arrays: 32
Element-wise square of arr4: [1 4 9]
Division of arr5 by arr4: [4.  2.5 2. ]
Element-wise square root of arr5: [2.         2.23606798 2.44948974]


In [50]:
# Numpy array operations
print("Logical AND of arr4 and arr5:", np.logical_and(arr4 > 1, arr5 < 6))
print("Logical OR of arr4 and arr5:", np.logical_or(arr1 < 4, arr5 > 5))
print("Logical NOT of arr4:", np.logical_not(arr4 > 2))



Logical AND of arr4 and arr5: [False  True False]
Logical OR of arr4 and arr5: [ True  True  True]
Logical NOT of arr4: [ True  True False]


In [51]:
# Numpy Universal Functions
arr6 = np.array([1, 2, 3])
arr7 = np.array([4, 5, 6])

print("Element-wise addition of arr6 and arr7:", np.add(arr6, arr7))
print("Element-wise subtraction of arr6 and arr7:", np.subtract(arr6, arr7))
print("Element-wise multiplication of arr6 and arr7:", np.multiply(arr6, arr7))
print("Element-wise division of arr6 and arr7:", np.divide(arr6, arr7))

print("Element-wise power of arr6 raised to arr7:", np.power(arr6, arr7))
print("Element-wise square root of arr7:", np.sqrt(arr7))
print("Element-wise logarithm of arr7:", np.log(arr7))
print("Element-wise exponential of arr6:", np.exp(arr6))

print("Element-wise absolute value of arr6:", np.abs(arr6))
print("Element-wise floor of arr6:", np.floor(arr6))
print("Element-wise ceiling of arr6:", np.ceil(arr6))
print("Element-wise rounding of arr6:", np.round(arr6))

print("Element-wise sine of arr6:", np.sin(arr6))
print("Element-wise cosine of arr6:", np.cos(arr6))
print("Element-wise tangent of arr6:", np.tan(arr6))


print("Element-wise hyperbolic sine of arr6:", np.sinh(arr6))
print("Element-wise hyperbolic cosine of arr6:", np.cosh(arr6))
print("Element-wise hyperbolic tangent of arr6:", np.tanh(arr6))



Element-wise addition of arr6 and arr7: [5 7 9]
Element-wise subtraction of arr6 and arr7: [-3 -3 -3]
Element-wise multiplication of arr6 and arr7: [ 4 10 18]
Element-wise division of arr6 and arr7: [0.25 0.4  0.5 ]
Element-wise power of arr6 raised to arr7: [  1  32 729]
Element-wise square root of arr7: [2.         2.23606798 2.44948974]
Element-wise logarithm of arr7: [1.38629436 1.60943791 1.79175947]
Element-wise exponential of arr6: [ 2.71828183  7.3890561  20.08553692]
Element-wise absolute value of arr6: [1 2 3]
Element-wise floor of arr6: [1 2 3]
Element-wise ceiling of arr6: [1 2 3]
Element-wise rounding of arr6: [1 2 3]
Element-wise sine of arr6: [0.84147098 0.90929743 0.14112001]
Element-wise cosine of arr6: [ 0.54030231 -0.41614684 -0.9899925 ]
Element-wise tangent of arr6: [ 1.55740772 -2.18503986 -0.14254654]
Element-wise hyperbolic sine of arr6: [ 1.17520119  3.62686041 10.01787493]
Element-wise hyperbolic cosine of arr6: [ 1.54308063  3.76219569 10.067662  ]
Element-wi

In [53]:
# Normalization and Standardization
arr8 = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr8)
std_dev = np.std(arr8)
print("Mean of arr8:", mean)
print("Standard deviation of arr8:", std_dev)

normalized_arr8 = (arr8 - mean) / std_dev
print("Normalized arr8:", normalized_arr8)

Mean of arr8: 3.0
Standard deviation of arr8: 1.4142135623730951
Normalized arr8: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [54]:
# One more way to normalize arr8 is to scale it to a range of [0, 1]
arr8_min = np.min(arr8)
arr8_max = np.max(arr8)
scaled_arr8 = (arr8 - arr8_min) / (arr8_max - arr8_min)
print("Scaled arr8 to range [0, 1]:", scaled_arr8)

# arr = np.array([1, 2, 3, 4, 5])
# # Min-Max Normalization
# min_max_norm = (arr - arr.min()) / (arr.max() - arr.min())
# # Z-score Normalization
# z_score_norm = (arr - arr.mean()) / arr.std()

Scaled arr8 to range [0, 1]: [0.   0.25 0.5  0.75 1.  ]


In [55]:
# Indexing and Slicing
arr9 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr9)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
arr9_slice = arr9[1:, 1:]  # Slicing to get a sub-array
print("Sliced array:\n", arr9_slice)

Sliced array:
 [[5 6]
 [8 9]]


In [57]:
Indexed_value = arr9[0, 1]  # Accessing a specific element
print("Element at (0, 1):", Indexed_value)

Element at (0, 1): 2


In [59]:
arr9[0,0] = 99
arr9

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [60]:
# Random Number Generation
random_arr = np.random.rand(3, 3)
print("Random array:\n", random_arr)

Random array:
 [[1.22087955e-01 3.56297838e-01 9.06828442e-01]
 [2.72132249e-01 6.47690121e-01 5.20376995e-04]
 [3.52568856e-01 3.04781258e-01 1.64655853e-01]]


In [63]:
#concatenation or stacking
arr10 = np.array([[1, 2], [3, 4]])
arr11 = np.array([[5, 6], [7, 8]])
concatenated_arr_axis0 = np.concatenate((arr10, arr11), axis=0)
concatenated_arr_axis1 = np.concatenate((arr10, arr11), axis=1)
print("Concatenated array along axis 0:\n", concatenated_arr_axis0)
print("Concatenated array along axis 1:\n", concatenated_arr_axis1)


Concatenated array along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated array along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Broadcasting in NumPy is a set of rules that allows operations between arrays of different 
# shapes and sizes without explicitly copying data.

# When performing operations (like addition, multiplication, etc.) on arrays with 
# different shapes, NumPy automatically "broadcasts" the smaller array across
# the larger one so their shapes are compatible.

a = np.array([1, 2, 3])        # Shape: (3,)
b = np.array([[10], [20], [30]]) # Shape: (3,1)

result = a + b
print(result)
# Output:
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]

# How it works:

# NumPy stretches the smaller array along the missing dimensions so both arrays have the same shape.
# No actual data is copied; it's a memory-efficient operation.
# Summary:
# Broadcasting makes array operations flexible and efficient, allowing you to perform calculations on arrays of different shapes.

[[11 12 13]
 [21 22 23]
 [31 32 33]]
